# Site settings
title: Matt Dodge
header-img: img/hero.jpg
email: matt@mattdodge.codes
copyright_name: Matt Dodge
description: >
  More than you want to know about Matt Dodge. No, not the punter.
baseurl: ""
url: "https://mattdodge.codes"
twitter_username: that314guy
github_username:  mattdodge
email_username:  hi@mattdodge.codes

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-3794533-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
